
SELECT TABLE1.COUNTRY,countrymax AS PLAYED ,numgoals FROM
(SELECT COUNTRY, COUNT(COUNTRY) numgoals FROM
    GOAL
 WHERE IS_PENALTY!=1
 GROUP BY COUNTRY) TABLE1
INNER JOIN
(SELECT COUNTRY, count(COUNTRY) countrymax FROM
    MATCH_PARTICIPANTS
 WHERE MATCH_ID IN (select MATCH_ID from PLAYED_MATCH)
 GROUP BY COUNTRY) TABLE2 ON TABLE1.COUNTRY = TABLE2.COUNTRY
;