
SELECT COUNTRY, SUM(SOLD) SOLD, CAST(SUM(REVENUE) AS DECIMAL(10,2)) REVENUE FROM
(SELECT MATCH_ID, COUNT(MATCH_ID)*0.5 SOLD, SUM(PRICE)*0.5 REVENUE FROM
    TICKET
 WHERE STATUS = 'SOLD'
 GROUP BY MATCH_ID
) TABLE1
JOIN MATCH_PARTICIPANTS ON TABLE1.MATCH_ID = MATCH_PARTICIPANTS.MATCH_ID
GROUP BY COUNTRY
;