
SELECT COUNTRY, SUM(SOLDT1) SOLD, CAST(SUM(REVENUET1) AS DECIMAL(10,2)) REVENUE FROM
(SELECT MATCH_ID, COUNT(MATCH_ID)*0.5 SOLDT1, SUM(PRICE)*0.5 REVENUET1 FROM
    TICKET
 WHERE STATUS = 'SOLD'
 GROUP BY MATCH_ID
) TABLE1
JOIN MATCH_PARTICIPANTS ON TABLE1.MATCH_ID = MATCH_PARTICIPANTS.MATCH_ID
GROUP BY COUNTRY
;