
SELECT COUNTRY, SUM(SOLD) SOLD,SUM(REVENUE) REVENUE FROM
(SELECT MATCH_ID, COUNT(MATCH_ID) SOLD, ROUND(SUM(PRICE)/2) REVENUE FROM
    TICKET
 WHERE STATUS = 'SOLD'
 GROUP BY MATCH_ID
) TABLE1
JOIN MATCH_PARTICIPANTS ON TABLE1.MATCH_ID = MATCH_PARTICIPANTS.MATCH_ID
GROUP BY COUNTRY
;