SELECT * FROM
BOOKING JOIN PLAYER ON BOOKING.COUNTRY = PLAYER.COUNTRY and BOOKING.SHIRT_NUM = PLAYER.SHIRT_NUM

;

SELECT PLAYER.NAME, COUNT(NAME) NUM_CARDS, PLAYER.SHIRT_NUM, PLAYER.COUNTRY FROM
BOOKING JOIN PLAYER ON BOOKING.COUNTRY = PLAYER.COUNTRY and BOOKING.SHIRT_NUM = PLAYER.SHIRT_NUM
group by PLAYER.NAME, PLAYER.SHIRT_NUM, PLAYER.COUNTRY
ORDER BY NUM_CARDS DESC, NAME ASC
LIMIT 5
;

