
SELECT TABLE1.MATCH_ID, CAST(GOAL_COUNT/PLAYED_MINUTES AS DECIMAL (5,3)) GOAL_PER_MINUTE FROM
(SELECT MATCH_ID, (MINUTE(DURATION)+HOUR(DURATION)*60)*1.0 PLAYED_MINUTES
 FROM PLAYED_MATCH) TABLE1
JOIN
(SELECT MATCH_ID, COUNT(MATCH_ID)*1.0 GOAL_COUNT FROM
    GOAL
 GROUP BY MATCH_ID) TABLE2 ON TABLE1.MATCH_ID = TABLE2.MATCH_ID
;