--make  query
-- returns the refs who gave out the most tickets
-- the name, and to which country is their most popular



SELECT REFEREE_ID, COUNT(REFEREE_ID) TARGET, COUNTRY, SHIRT_NUM FROM
    BOOKING
group by REFEREE_ID, COUNTRY, SHIRT_NUM;


SELECT DISTINCT REFEREE_ID, MAX(TARGETT1)TARGET FROM
(SELECT REFEREE_ID, COUNT(REFEREE_ID) TARGETT1, COUNTRY, SHIRT_NUM FROM
    BOOKING
 group by REFEREE_ID, COUNTRY, SHIRT_NUM)
group by REFEREE_ID
;

SELECT NAME, COUNT(NAME) CARDS FROM
PLAYER JOIN BOOKING on PLAYER.COUNTRY = BOOKING.COUNTRY and PLAYER.SHIRT_NUM = BOOKING.SHIRT_NUM
group by NAME
ORDER BY CARDS DESC
;

SELECT REFEREE_ID, NAME PLAYERNAME, COUNT(NAME) CARDS FROM
    PLAYER JOIN BOOKING on PLAYER.COUNTRY = BOOKING.COUNTRY and PLAYER.SHIRT_NUM = BOOKING.SHIRT_NUM
group by REFEREE_ID, NAME
ORDER BY CARDS DESC, REFEREE_ID ASC
;